var folders=[
"edm", 
"normal" 
];
var clips=[
[
"music/edm/2nd Life Sara Brown - Ashes (Magic Free Release)-IFVCiJFvn4s.webm",
"music/edm/Ahrix - Nova-Rq-0NxKUR-Y.webm",
"music/edm/Alex Skrindo and Stahl! - Moments [NCS Release]-IHtL_BKO804.webm",
"music/edm/Altero - Feeling-K0EEbYUq1H8.webm",
"music/edm/Anikdote - Victim (ft. Aminita Francis) (Magic Free Release)-B6PgdWybbow.webm",
"music/edm/Anna Yvette and AFK - Clouds [NCS Release]-KeU2pyfBz1E.webm",
"music/edm/Arc North - Limbo (ft. Veronica Bravo)-YHhmSrevpAE.webm",
"music/edm/Arlow - How Do You Know [NCS Release]-2mcwNXVHqlI.webm",
"music/edm/Ascence - Konnichiwa [NCS Release]-5eR1iOEp1oU.webm",
"music/edm/Ascence - Places Like That [NCS Release]-jmpRflEHdqs.webm",
"music/edm/Au5 and AMIDY - Way Down (feat. Karra) [Monstercat Release]-enqFqx-9p6Y.webm",
"music/edm/AVE and EFX & Varun - Paint the Sky (feat. LA James)-MwhVsOKxoko.webm",
"music/edm/AWAY - Sleepwalker (DROELOE Remix) ft. London Thor-eFicAasyZYs.webm",
"music/edm/Axol x Alex Skrindo - You [NCS Release]-sA_p0rQtDXE.webm",
"music/edm/BEAUZ & Momo - Won't Look Back [NCS Release]-HbYXIMFDoRg.webm",
"music/edm/BEAUZ - Memories (Official Audio) ft. Linney-iBK1-H68jBM.webm",
"music/edm/BEAUZ and JVNA - Crazy [NCS Release]-xgcLwtGlgLU.webm",
"music/edm/Besomorph & Arcando & Neoni - Army [NCS Release]-4EDOIftYA4A.webm",
"music/edm/Besomorph & Biometrix - Wilted (feat. Bolshiee)-4Eb-98r1aN0.webm",
"music/edm/Besomorph & Biometrix - Wilted (feat. Bolshiee)-YBj974fK1-4.webm",
"music/edm/Besomorph & Coopex - Redemption (ft. Riell) [NCS Release]-ZGrWry_4Q8s.webm",
"music/edm/Besomorph & Riell - Nobody-k2j9oU0u1tM.webm",
"music/edm/Besomorph & RIELL - Who Am I (Lyrics)-P49x9lR-FKA.webm",
"music/edm/Besomorph - Monster-iIaj7qY5Yvs.webm",
"music/edm/Besomorph - Scream (feat. Riell)-R3TypuL-k4Q.webm",
"music/edm/Besomorph - Scream (feat. Riell)-VxN5CozlPVo.webm",
"music/edm/Besomorph - White Line (feat. Anna Pancaldi)-SSLhC4WGMsw.webm",
"music/edm/Best Music Mix 2020 Best Remixes Of EDM Gaming Music Mix 2020 New Electro House Music-kMAN5pDNpZ0.webm",
"music/edm/Biometrix - Shameless (Ft. Bolshiee) (INFINITY BASS) #enjoybeauty-IJ5ESYRXrBQ.webm",
"music/edm/BIOMETRIX x NBLM - GRAVITY (feat. MVRT)-3SmodDU5m4A.webm",
"music/edm/BOXINBOX & Lionsize - Black and White (feat. MJ Ultra)-ugpvZ61CnD8.webm",
"music/edm/Braken - Wherever You Go [Monstercat Release]-IsFnnTbrOIs.webm",
"music/edm/BRAN & ADAD - Stranger (BASS BOOSTED)-sjIGzxHBMVA.webm",
"music/edm/BRAN & ADAD - Stranger (Magic Free Release)-Hf8tIe5ZX-Q.webm",
"music/edm/BRAN - In the Dark-dC9iihBR3W8.webm",
"music/edm/BRAN - Never Enough-HedwTLb5rjM.webm",
"music/edm/BVRNOUT & KROMATIKS - Follow Your Heart (feat. Cadence Ludden)-SWjQR9HsX7o.webm",
"music/edm/Cartoon - C U Again feat. Mikk Mae (Cartoon vs Futuristik VIP) [NCS Release]-NJNp6DnAAIo.webm",
"music/edm/Cartoon - On & On (feat. Daniel Levi) [NCS Release]-K4DyBUG242c.webm",
"music/edm/Cartoon - Why We Lose (feat. Coleman Trapp) [NCS Release]-zyXmsVwZqX4.webm",
"music/edm/Catas & Kasger - Blueshift [NCS Release]-_C1dfBeo374.webm",
"music/edm/Cemre Emin & Berfin - All In My Head (Magic Free Release)-meTo42vHYZ8.webm",
"music/edm/CloudNone & Elle Vee - Out There [Monstercat Release]-0nioO0MM7-w.webm",
"music/edm/Conro - Remember You [Monstercat Release]-MeWqUep7gZ8.webm",
"music/edm/Coopex & KHEMIS - Dark Blue Paradise (ft. MEL)-Ubi4dOpvMHg.webm",
"music/edm/Coopex - I Miss You [NCS Release]-L6ZSUyI9tx4.webm",
"music/edm/Culture Code - Fairytale (feat. Amanda Collis)  [NCS Release]-qVAFNx1WRWE.webm",
"music/edm/Culture Code - Make Me Move (feat. Karra) [NCS Release]-vBGiFtb8Rpw.webm",
"music/edm/Debris & Jonth - Game Time [NCS Release]-yDTvvOTie0w.webm",
"music/edm/Defqwop - Awakening [NCS Release]-B-m7X1-T1hQ.webm",
"music/edm/Desmeon - Hellcat [NCS Release]-JSY6vBPunpY.webm",
"music/edm/Desmeon - On That Day (feat. ElDiablo, Flint & Zadik) [NCS Release]-PUpS-ZrrZnU.webm",
"music/edm/Despotem x Codi - Never Left U (Magic Free Release)-8CqBd6VOgkA.webm",
"music/edm/DG812 - In Your Eyes _ Magic Music Release-vP4zGMdTDPM.webm",
"music/edm/Diamond Eyes - Everything [NCS Release]-_XspQUK22-U.webm",
"music/edm/Diamond Eyes - Flutter [NCS Release]-lEHM9HZf0IA.webm",
"music/edm/Diamond Eyes - Gravity [NCS Release]-WWtpK0hwVdk.webm",
"music/edm/Diamond Eyes - Stars [NCS Release]-Fmf-G9fpwto.webm",
"music/edm/Different Heaven & EH!DE - My Heart [NCS Release]-jK2aIUmmdP4.webm",
"music/edm/Different Heaven & Sian Area - Feel Like Horrible [NCS Release]-lm4OJxGQm_E.webm",
"music/edm/Different Heaven - Nekozilla (LFZ Remix) [NCS Release]-4ZvnbsfXRk0.webm",
"music/edm/Different Heaven - Pentakill (ft. ReesaLunn) [Official Video]-Rpr_HNJ0Y3A.webm",
"music/edm/Different Heaven - Safe And Sound [NCS Release]-13ARO0HDZsQ.webm",
"music/edm/Dion Timmer - Internet Boy (feat. Micah Martin) [Monstercat Release]-cRJQfydRKZQ.webm",
"music/edm/Dion Timmer - Lost [Monstercat Release]-HK8Xv8ZQJEo.webm",
"music/edm/Dirty Palm - No Stopping Love [NCS Release]-xFoGtSiqins.webm",
"music/edm/Disero - Like That (feat. Josh Smith) [Monstercat Release]-OGdLFsCgEJc.webm",
"music/edm/Disfigure - Blank VIP (feat. Tara Louise) [NCS Release]-j5DCb1ycXyA.webm",
"music/edm/Disfigure - Blank [NCS Release]-p7ZsBPK656s.webm",
"music/edm/Disfigure - Hollah! [NCS Release]-m0ZXoiIZ40U.webm",
"music/edm/DJ ASSASS1N - Frag Out-6jARhgo0cCA.webm",
"music/edm/Dominic Strike - Heartbeat (Magic Free Release)-Mc_f1j5u0y4.webm",
"music/edm/Duumu - You Say (feat. Pauline Herr) [Monstercat Release]-GuHVAsJ_t2E.webm",
"music/edm/Egzod - Rise Up (ft. Veronica Bravo & M.I.M.E) [NCS Release]-aifDMH1p3zw.webm",
"music/edm/Elektronomia - Energy-2wml6eoLQ0U.webm",
"music/edm/Elektronomia - Sky High [NCS Release]-TW9d8vYrVFQ.webm",
"music/edm/Elektronomia - Summersong 2018 [NCS Release]-HoCw_gaCHXE.webm",
"music/edm/EMDI x ROGUENETHVN - Let Your Heartbreak (feat. Leo the Kind) [NCS Release]-fCODoi9feMo.webm",
"music/edm/Ephixa & Going Quantum - Let's Roll [Monstercat Release]-o-ins2ph7S4.webm",
"music/edm/Fabian Mazur & Snavs - Arena-iqqkxCGvmpo.webm",
"music/edm/Fabian Mazur - Sun Goes Down-IqrZSrR75lQ.webm",
"music/edm/FadeX - Pokemon Riot-fCw-dtNTlcI.webm",
"music/edm/Fairlane - Uncover You (feat. Ilsey)-h2xlOuKwCUc.webm",
"music/edm/Fairlane - Wildfire (feat. Nevve)-b9WSA8UThJA.webm",
"music/edm/Far Out - New Beginning-frX8kNaPeKU.webm",
"music/edm/Feels Good To Be A Trap King (Goblin Mashup)-b6gOauq-87M.webm",
"music/edm/Felmax - Chapel-aJq4tmJ674Q.webm",
"music/edm/Floatinurboat - Limbo (feat. ELIOTT) [NCS Release]-n2kldFRUCpM.webm",
"music/edm/floatinurboat - Spirit of Things [NCS Release]-LY1ik-Do_MU.webm",
"music/edm/Geoxor - You & I [NCS Release]-1lcc21RQx_A.webm",
"music/edm/Ghasper - Turtle Ship-1b2we5jOKXA.webm",
"music/edm/Giraffe Squad - Wait For Me [NCS Release]-rgW_I8saK1o.webm",
"music/edm/Heuse & Zeus x Crona - Pill (feat. Emma Sameth) [NCS Release]-CLiXUT3MS34.webm",
"music/edm/Heuse - Stones (feat. Chris Linton & Emma Sameth) [NCS Release]-XY28M0dIx6o.webm",
"music/edm/Hopsteady - Feel Me (feat. Elora Zamar)-28fwRhdjy1g.webm",
"music/edm/it's different - Shadows (feat. Miss Mary) [NCS Release]-UHbDJ1oPuGo.webm",
"music/edm/Itro & Tobu - Cloud 9 [NCS Release]-VtKbiyyVZks.webm",
"music/edm/IZECOLD - Close (feat. Molly Ann) [Brooks Remix] _ NCS x FHM Release-bzehQ60b3XI.webm",
"music/edm/Janji - Heroes Tonight (feat. Johnning) [NCS Release]-3nQNiWdeH2Q.webm",
"music/edm/JayKode - Careful (feat. Sam Bruno)-b1sd9hxFXTE.webm",
"music/edm/JayKode - Know Better (feat. Mister Blonde)-STgM16LNsMk.webm",
"music/edm/Jim Yosef & Anna Yvette - Linked [NCS Release]-yHLtE1wFeRQ.webm",
"music/edm/Jim Yosef - Arrow [NCS Release]-5LI5QZVUU98.webm",
"music/edm/Jim Yosef - Firefly [NCS Release]-x_OwcYTNbHs.webm",
"music/edm/Jim Yosef - Lights [NCS Release]-vb3ks4WllXA.webm",
"music/edm/Jim Yosef - Moonlight [NCS Release]-MvTYrjX4ve4.webm",
"music/edm/Jimmy Hardwind - Want Me (feat. Mike Archangelo)--Rw8zR9wmTY.webm",
"music/edm/Jinco & FURY - Far Sight (feat. Holly Jade) [Bass Boosted]-AF3C-CyVxng.webm",
"music/edm/Jo Cohen & BQ - Glowing At Night [NCS Release]-bwrCCc6hWKo.webm",
"music/edm/Jo Cohen & Sex Whales - Run Away (feat. Lusil) [NCS Release]-wHHSN6tdeZI.webm",
"music/edm/Jo Cohen & Sex Whales - We Are [NCS Release]-C6IaUMAg3Dc.webm",
"music/edm/Jordan Comolli - 4U-N_RY1Od8s_Q.webm",
"music/edm/JPB - Defeat The Night (feat. Ashley Apollodor) [NCS Release]-A_AtqKMqPUE.webm",
"music/edm/JPB - High [NCS Release]-Tv6WImqSuxA.webm",
"music/edm/Julius Dreisig & Zeus X Crona - Invisible [NCS Release]-QglaLzo_aPk.webm",
"music/edm/K-391 - Dream Of Something Sweet ft. Cory Friesenhan [Privated NCS Release]-O9yeYhmXCAQ.webm",
"music/edm/Kalide & Peter Kiemann - Forever (ft  Bianca) [Magic Free Release]-mGfOSA7UIdU.webm",
"music/edm/Kasger - Reflections [NCS Release]-M4_ivwYfWFo.webm",
"music/edm/Khamix - Exura (VIP) (Magic Free Release)-mRFX8AcDuMo.webm",
"music/edm/KIRA - New World [NCS Release]-6nCSYh8vwv0.webm",
"music/edm/Kontinuum - Lost (feat. Savoi) [NCS Release]-89IUAznfjqE.webm",
"music/edm/Krys Talk & Cole Sipe - Way Back Home [NCS Release]-qrmc7KVIoKQ.webm",
"music/edm/Krys Talk - Fly Away [NCS Release]-LfDfb-87F_s.webm",
"music/edm/KUURO - Take Me Down (feat. Bianca) [Monstercat Release]-mPerS_QhVLI.webm",
"music/edm/Laszlo - Fall To Light [NCS Release]-Lq2UrnDsI_s.webm",
"music/edm/Laszlo - Here We Are [NCS Release]-NfuTWnIXad0.webm",
"music/edm/Le Malls - Blazed (feat. Beckii Power)-UrJ9ComH1Sc.webm",
"music/edm/Legends Never Die - Remix (ft. Alan Walker) _ Worlds 2017 - League of Legends-eEKfWVvADiQ.webm",
"music/edm/Lensko - Cetus [NCS Release]-i3vrV-WNmsc.webm",
"music/edm/Lensko - Circles [NCS Release]-ztvIhqVtrrw.webm",
"music/edm/Lensko - Let's Go! [NCS Release]-mSLuJYtl89Y.webm",
"music/edm/LFZ - Popsicle [NCS Release]-K8DUjObr_tU.webm",
"music/edm/Light Years Away - Melrose At Midnight [NCS Release]-KLtn2qA7WxE.webm",
"music/edm/Lost Sky - Dreams pt. II (feat. Sara Skinner) [NCS Release]-L7kF4MXXCoA.webm",
"music/edm/Lost Sky - Dreams [NCS Release]-SHFTHDncw0g.webm",
"music/edm/Lost Sky - Fearless pt.II (feat. Chris Linton) [NCS Release]-S19UcWdOA-I.webm",
"music/edm/Lost Sky - Lost [NCS Release]-h-nHdqC3pPs.webm",
"music/edm/Lost Sky - Where We Started (feat. Jex) [NCS Release]-U9pGr6KMdyg.webm",
"music/edm/Lost years -West side lane-RCyOUR2FbU8.webm",
"music/edm/Maduk - Go Home [NCS Release]-qScpgKbuTLw.webm",
"music/edm/Mandrazo & MOHA - WASTED (ft. Halfway) (Magic Free Release)-gs-SkhsHXnI.webm",
"music/edm/Marin Hoxha & Caravn - Eternal [NCS Release]-hECg1-wUyKg.webm",
"music/edm/Marin Hoxha x Invent - Lost On The Way (ft. Caravn) (Magic Free Release)-ykIwoy3Xsw0.webm",
"music/edm/Matthew Blake feat. Katie Boyle - Saved Me Now [NCS Release]-EKNjECcosJc.webm",
"music/edm/Max Brhon - Humanity [NCS Release]-OJhqsUnKUWw.webm",
"music/edm/MDK - Super Ultra [FREE DOWNLOAD]-PLEQGywWbV0.webm",
"music/edm/Mendum - Elysium [NCS Release]-3PS5jAMkCmU.webm",
"music/edm/Meric - Take Off (feat. Paul Rey)-VcUWXvdsfOc.webm",
"music/edm/MYRNE - Lyra [Monstercat Release]-uw8VQokwBsI.webm",
"music/edm/NCT x T & Sugah - Along The Road (feat. Voicians) [NCS Release]-oDdR6Tm-U0c.webm",
"music/edm/NEFFEX - Best of Me [Official Video]-0Wa_CR0H8g4.webm",
"music/edm/NEFFEX - Coming For You[Copyright Free]-xPi1O8g8zII.webm",
"music/edm/NEFFEX - Destiny   [Copyright Free]-24C8r8JupYY.webm",
"music/edm/NEFFEX - Life [Copyright Free]-TPCaWQQo11A.webm",
"music/edm/NEFFEX - Rumors (Lyrics)-9XNYqOJmqHU.webm",
"music/edm/NEFFEX - Runaway [Copyright Free]-K65tOxcboF4.webm",
"music/edm/NEFFEX - Soldier [Copyright Free]-Ccsh_-Cucl4.webm",
"music/edm/NEFFEX- Failure[Copyright Free]-YKqDiNJJPXk.webm",
"music/edm/Nimi Dovrat - Run With You (ft Shannon Lawn) (Magic Free Release)-Hkt7_aX0NcY.webm",
"music/edm/NIVIRO - Flashes [NCS Release]-I8TyTCZ_5jI.webm",
"music/edm/NOAX & Calli Boom - Focused-t-jY-nYciLo.webm",
"music/edm/Nurko - Let Me Go (feat. Alina Renae)-sEl2a2ZEoKo.webm",
"music/edm/Nytrix & Kaskobi - Memories Are Loud (Magic Free Release)-Jce69sMpfDk.webm",
"music/edm/Omar Varela, Xavi & Gi - Stronger (feat. Miss Lina) [NCS Release]-ix1nKNZfr0s.webm",
"music/edm/OMFG - Hello ( Zepidix & Monkid Raves Remix )-4i18KjGUpoM.webm",
"music/edm/OmgLoSteve - Too Late ft. Addie Nicole _ Copyright Free Music-LGJc37IPQ-I.webm",
"music/edm/Outr3ach & Riell - Damage (Lyrics)-OdNy5mQyBuY.webm",
"music/edm/Panda Eyes - Vortex-xKD6DEKB0iw.webm",
"music/edm/Paris Blohm - Into Dust (feat. Elle Vee)-WVevzJk6mDc.webm",
"music/edm/Paris Blohm - Let Me Go (feat. KARRA)-gaQYDVd5Ka8.webm",
"music/edm/Paul Flint - Savage [NCS Release]-8uSx3DyJjk0.webm",
"music/edm/Paul Garzon - Survivors (Magic Free Release)-EYlUYdNBy3s.webm",
"music/edm/Phantom Sage - Holystone-O5ZN3_svgs0.webm",
"music/edm/Prismo - Stronger [NCS Release]-IIwiM777OzQ.webm",
"music/edm/Prismo - Weakness [NCS Release]-SvRFNNbxuAk.webm",
"music/edm/PsoGnar - The Great Deception-QyxKkaUXZjE.webm",
"music/edm/Raiko - Lightning Child (feat. Remi Willow) [NCS Release]-UZrgVfa8Jzc.webm",
"music/edm/RedMoon & Meron Ryan - Heavyweight [NCS Release]-otD-XbAhMbU.webm",
"music/edm/Rival & Cadmium - Seasons (Lyrics _ Lyric Video) feat. Harley Bird-p9rdUc_pgWU.webm",
"music/edm/Rival x Cadmium - Doubt You (ft. Natalie Holmes) [Official Lyric Video]-G8S4O_8K-Uw.webm",
"music/edm/Rival x Egzod - Live A Lie (ft. Andreas Stone) [NCS Release]-GpoYRPA7YFw.webm",
"music/edm/Rob Gasser - Superhero (feat. Sekai) [NCS Release]-8W45hw6mApI.webm",
"music/edm/Rob Gasser - Wrong Answer-AhYIHnwGbe8.webm",
"music/edm/ROY KNOX - Earthquake [NCS Release]-z_m0wtLMfdU.webm",
"music/edm/ROY KNOX - Firefly (Magic Free Release)-JPsWAmdpxco.webm",
"music/edm/ROY KNOX - Lost In Sound (Magic Free Release)-bafd5CsNk0M.webm",
"music/edm/ROY KNOX x WTCHOUT - Shadows (Feat. Svniivan) [NCS Release]-o8Y_uR6ZDxo.webm",
"music/edm/RudeLies & Facading - Arabian Nights [NCS Release]-g-PtIjywmac.webm",
"music/edm/Sabai - Million Days (feat. Hoang & Claire Ridgely) [Monstercat Release]-KAcBeqcTMHg.webm",
"music/edm/Satara - The Game (Magic Free Release)-zudhh_9Bve0.webm",
"music/edm/Ship Wrek & Zookeepers - Ark [NCS Release]-8xlDwukxjnA.webm",
"music/edm/Simbai & Eyemer - Thunder [NCS Release]-A3nIwjUehS0.webm",
"music/edm/SirensCeol - Coming Home [NCS Release]-0ewGL1NpD84.webm",
"music/edm/Skvor - Shine (Magic Free Release)-1QVXuE4HY-Y.webm",
"music/edm/SKYL1NK - The Wizard [NCS Release]-yQYFNdyS3fc.webm",
"music/edm/Slushii - Dreaming Of You-aAngdXj_f2g.webm",
"music/edm/Slushii - Far Away-1g7GDOR0ZhI.webm",
"music/edm/Spektrem - Shine (Gabriel Drew & Bloom Remix) [NCS Release]-rWVjht-MIto.webm",
"music/edm/Spektrem - Shine [NCS Release]-n4tK7LYFxI0.webm",
"music/edm/Stahl - Pushed Down (feat. Caroline)-fIqh30L_k7I.webm",
"music/edm/Stereohats, Folded Dragons - Army (Feat. Amanda Yang)-i9hg8TpOZd4.webm",
"music/edm/Stonebank - What Are You Waiting For [Monstercat Release]-n2qgc8vF8sU.webm",
"music/edm/Sub Urban - Cradles [NCS Release]-Hn4sfC2PbhI.webm",
"music/edm/Summer Was Fun & Laura Brehm - Prism [NCS Release]-Jp1Ka8ZmNFQ.webm",
"music/edm/Take_Five - Tell Me-Kx1QIlGmhPo.webm",
"music/edm/Taska Black - Nothing Lasts (feat. Pauline Herr)-io-lz1zvV-A.webm",
"music/edm/Teminite & Panda Eyes - Highscore-Qg1qZq5yjps.webm",
"music/edm/The FifthGuys & Glitchedout- My Lane (ft. Tim Moyo) [Magic Free Release]-QIw9quAhWEw.webm",
"music/edm/The Lifted - Watch Me Fall (feat. Ashliann)-cwPHx0bPL7A.webm",
"music/edm/TheFatRat & Anjulie - Close To The Sun-oJuGlqO85YI.webm",
"music/edm/TheFatRat - Fly Away feat. Anjulie-cMg8KaMdDYo.webm",
"music/edm/TheFatRat - Monody (feat. Laura Brehm)-B7xai5u_tnk.webm",
"music/edm/TheFatRat - Rise Up-j-2DGYNXRx0.webm",
"music/edm/Tobu & Itro - Sunburst [NCS Release]-4lXBHD5C8do.webm",
"music/edm/Tobu - Hope [NCS Release]-EP625xQIGzs.webm",
"music/edm/Tobu - Infectious [NCS Release]-ux8-EbW6DUI.webm",
"music/edm/Tobu - Turn It Up [NCS Release]-RrtAC7UZOh0.webm",
"music/edm/Tokyo Machine - SPOOKY [Monstercat Release]-qZcR_afc1Mw.webm",
"music/edm/Trigger Not Alone (Goblin Mashup)-AOH8iGLOErY.webm",
"music/edm/Trivecta - Tornado (feat. Monika Santucci) [Monstercat Release]-KIZxJdSgI0I.webm",
"music/edm/TWERL & DEVAULT - Lishu-geP_SYJZGBA.webm",
"music/edm/Unknown Brain & Spce CadeX - Holding You (feat. Max Landry) [NCS Release]-Nn2aXfUkJsc.webm",
"music/edm/Unknown Brain - Inspiration (feat. Aviella) [NCS Release]-aCH1eyWq9B0.webm",
"music/edm/Unknown Brain - Like Home (feat. Trove)--N2vyObWnuQ.webm",
"music/edm/Unknown Brain - Perfect 10 (feat. Heather Sommer) [NCS Lyric Video]-AEVaK0e1kTE.webm",
"music/edm/Unknown Brain - Say Goodbye (ft. Marvin Divine) [NCS Release]-rdD-DMTWqU4.webm",
"music/edm/Unknown Brain - Superhero (feat. Chris Linton) [NCS Release]-LHvYrn3FAgI.webm",
"music/edm/Unknown Brain - War Zone (ft. M.I.M.E.) [NCS Release]-d7JoJcEJYzY.webm",
"music/edm/Unknown Brain - Why Do I (feat. Bri Tolani) [NCS Release]-tcHJodG5hX8.webm",
"music/edm/Unknown Brain - Why Do I (feat. Bri Tolani)-AaTzdjVidLs.webm",
"music/edm/Unknown Brain x Rival - Control (feat. Jex) [NCS Release]-bLZHcnuqscU.webm",
"music/edm/Unknown Brain, Heather Sommer - Perfect 10 (Unknown Brain & RudeLies VIP) [NCS Release]-xahgjUd9nx4.webm",
"music/edm/Valence - Infinite [NCS Release]-QHoqD47gQG8.webm",
"music/edm/Vanze - Survive (feat. Neon Dreams) [NCS Release]-cvl8e2se8Q4.webm",
"music/edm/Venemy - Need You Now (feat. Danica) [NCS Release]-li_tpwcMEQQ.webm",
"music/edm/Vexento - Forever-utShaFeGEfo.webm",
"music/edm/Vexento - Masked Heroes-ZLhfr8mpzxU.webm",
"music/edm/Vexento - Sunrise-HlSopqiw0k0.webm",
"music/edm/Vicetone - Walk Thru Fire (Lyrics) ft. Meron Ryan-kRauptdx_Is.webm",
"music/edm/Voicians - Seconds [NCS Release]-8cuMg3Hqxzo.webm",
"music/edm/Warriyo - Mortals (feat. Laura Brehm) [NCS Release]-yJg-Y5byMMw.webm",
"music/edm/WiDE AWAKE - Ready [Bass Boosted]-uOCh0bIRtXo.webm",
"music/edm/William Black - Hallucinate (Lyrics) ft. Nevve-b36MW3vSySk.webm",
"music/edm/William Black x Rico & Miella - Here At Last-lIsfer_52L4.webm",
"music/edm/WOLFE - Under the Covers (feat. Emma Sameth)-xFOzVwjoFQE.webm",
"music/edm/Wontolla, Kasger & Limitless - Miles Away [NCS Release]-aCyQu00rZrM.webm",
"music/edm/X-Ziliot - Never Be Alone-tklK5sBqnJA.webm",
"music/edm/Y&V - Back In Time [NCS Release]-VuSbd-N0z8c.webm",
"music/edm/Yusuf Alev - Yoros (Magic Free Release)-Ar50xVQ08Qw.webm",
"music/edm/Zaza - Be Together [NCS Release]-gEbRqpFkTBk.webm",
"music/edm/[DnB] - Rameses B - Darkest Place (feat. Aloma Steele) [Monstercat Release]-UaerdFeq32E.webm",
"music/edm/[Dubstep] - Slushii - Emptiness [Monstercat Release]-QqHgX36qEFs.webm",
"music/edm/[Dubstep]Evilwave - Live Is Life-Jr97e-V6se4.webm",
"music/edm/[Trap] - Aero Chord And Klaypex - Be Free [Monstercat Release]-fbk_BGXOe-I.webm",
"music/edm/[Trap] - Snavs - Time [Monstercat Release]-UwbVx-XTubM.webm"
],
[
"music/normal/'Bassa Sababa' NETTA GROMEE REMIX-HckBFNuG_Cs.webm",
"music/normal/Alan Walker - All Falls Down (feat. Noah Cyrus with Digital Farm Animals)-6RLLOEzdxsM.webm",
"music/normal/Alan Walker - Alone-1-xGerv5FOk.webm",
"music/normal/Alan Walker - Darkside (feat. Au_Ra and Tomine Harket)-M-P4QBt-FWw.webm",
"music/normal/Alan Walker - Diamond Heart (feat. Sophia Somajo)-sJXZ9Dok7u8.webm",
"music/normal/Alan Walker - Faded-60ItHLz5WEA.webm",
"music/normal/Alan Walker - Force-lqYQXIt4SpA.webm",
"music/normal/Alan Walker - Sing Me To Sleep-2i2khp_npdE.webm",
"music/normal/Alan Walker - The Spectre-wJnBTPUQS5A.webm",
"music/normal/Armin van Buuren - Blah Blah Blah (Official Lyric Video)-mfJhMfOPWdE.webm",
"music/normal/ARY - Childhood Dreams (Cover by Seraphine)-0F5YSRWe7FI.webm",
"music/normal/Bingo Players ft. Far East Movement - Get Up (Rattle) (Official Video)-6_BGKyAKigs.webm",
"music/normal/Box Of Black Pearls Kitty Lingmerth-g7yuRREJJAo.webm",
"music/normal/Burak Yeter & Cecilia Krull - My Life Is Going On (Burak Yeter Remix) (Lyric Video)-qBDyiZ8ZXWI.webm",
"music/normal/C-BooL - Fire In My Head ft. Cadence XYZ (Official Video)-P_2FdaTto7Y.webm",
"music/normal/Calvin Harris - I Need Your Love (Official Video) ft. Ellie Goulding-AtKZKl7Bgu0.webm",
"music/normal/Calvin Harris - Outside (Official Video) ft. Ellie Goulding-J9NQFACZYEU.webm",
"music/normal/Calvin Harris - Summer (Official Video)-ebXbLfLACGM.webm",
"music/normal/Calvin Harris - Sweet Nothing (Official Video) ft. Florence Welch-17ozSeGw-fY.webm",
"music/normal/CHROMANCE - Wrap Me In Plastic (Marcus Layton Edit)-nvrrePT-uVY.webm",
"music/normal/College & Electric Youth - A Real Hero (Drive Original Movie Soundtrack)--DSVDcw6iW8.webm",
"music/normal/David Guetta & Showtek - Bad ft.Vassy (Lyrics Video)-oC-GflRB0y4.webm",
"music/normal/David Guetta & Showtek - Your Love (Lyric video)-VKtTSoC7o2I.webm",
"music/normal/David Guetta - Dangerous (Official video) ft Sam Martin-EVr__5Addjw.webm",
"music/normal/David Guetta - Hey Mama (Official Video) ft Nicki Minaj, Bebe Rexha & Afrojack-uO59tfQ2TbA.webm",
"music/normal/David Guetta - Titanium ft. Sia (Official Video)-JRfuAukYTKg.webm",
"music/normal/David Guetta Feat. Kid Cudi - Memories (Official Video)-NUVCQXMUVnI.webm",
"music/normal/David Guetta ft Justin Bieber - 2U (The Victorias Secret Angels Lip Sync)-RqcjBLMaWCg.webm",
"music/normal/David Guetta, Brooks & Loote - Better When You're Gone (Lyric Video)--OrSxiUHk4E.webm",
"music/normal/David Guetta, Martin Garrix & Brooks - Like I Do (Lyric Video)-WfPu9Jrcpuk.webm",
"music/normal/Deorro x Chris Brown - Five More Hours (Official Video)-j3CaHeakZF4.webm",
"music/normal/Dimitri Vegas, MOGUAI & Like Mike - Mammoth (Original Mix)-_o-XIryB2gg.webm",
"music/normal/DJ Antoine vs Mad Mark feat. B-Case & U-Jean - House Party (Official Video HD) [Lyrics]-pQAyeQQOzNk.webm",
"music/normal/DJ Snake, Lil Jon - Turn Down for What-HMUDVMiITOU.webm",
"music/normal/Don Diablo - Survive (Lyric Video) ft. Emeli Sande, Gucci Mane-loB1bMXzvJ4.webm",
"music/normal/Dua Lipa - Hallucinate (Official Music Video)-qcZ7e9EOQTY.webm",
"music/normal/Dua Lipa - Physical (Official Video)-9HDEHj2yzew.webm",
"music/normal/Electric Youth & College - A Real Hero (DRIVE)-XoHI6Zus2UI.webm",
"music/normal/Eurythmics, Annie Lennox, Dave Stewart - Sweet Dreams (Are Made Of This) (Official Video)-qeMFqkcPYcg.webm",
"music/normal/Evanescence - Bring Me To Life (Official Music Video)-3YxaaGgTQYM.webm",
"music/normal/EvenS - Tell-OUZN0z0d1Ps.webm",
"music/normal/Flume - Heater-PUX-VCGAsD8.webm",
"music/normal/Galantis -  Peanut Butter Jelly (Official Video)-4jBDnYE1WjI.webm",
"music/normal/Galantis - No Money (Official Video)-xUVz4nRmxn4.webm",
"music/normal/Galantis - Runaway (U & I) (Official Video)-5XR7naZ_zZA.webm",
"music/normal/In The End [Official HD Music Video] - Linkin Park-eVTXPUF4Oz4.webm",
"music/normal/ItaloBrothers - Welcome To The Dancefloor (Official Video HD)-3ITQf6Ve7Nc.webm",
"music/normal/Jetta - I'd Love to Change the World (Matstubs Remix)-5hEh9LiSzow.webm",
"music/normal/Jovani - Keep It To Myself (feat. Jazzu)-KCm4H6SnaI8.webm",
"music/normal/K-391 & Alan Walker - Ignite (feat. Julie Bergan & Seungri)-Az-mGR-CehY.webm",
"music/normal/Kanye West - Stronger-PsO6ZnUZI0g.webm",
"music/normal/Kitty Lingmerth - Let The Sky Fall (Original Audio)-9_G50WTYva8.webm",
"music/normal/Kris Kross Amsterdam x The Boy Next Door - Whenever (feat. Conor Maynard) [Official Music Video]-heVJaMvCmR0.webm",
"music/normal/LMFAO ft. Lauren Bennett, GoonRock - Party Rock Anthem (Official Video)-KQ6zr6kCPj8.webm",
"music/normal/LUM!X, Gabry Ponte - Monster (Official Music Video)-VWNFj9rm6tc.webm",
"music/normal/M.I.A. - Paper Planes-ewRjZoRtu0Y.webm",
"music/normal/MACKLEMORE & RYAN LEWIS - CAN'T HOLD US FEAT. RAY DALTON (OFFICIAL MUSIC VIDEO)-2zNSgSzhBfM.webm",
"music/normal/Madison Mars - New Vibe Who Dis (feat. Little League) [Official Lyric Video]-FXZ1xjCCCDk.webm",
"music/normal/Major Lazer & DJ Snake - Lean On (feat. MO) (Official Music Video)-YqeW9_5kURI.webm",
"music/normal/Martin Garrix & David Guetta - So Far Away (Official Video) feat. Jamie Scott & Romy Dya-o7iL2KzDh38.webm",
"music/normal/Martin Garrix & Justin Mylo - Burn Out (Official Video) feat. Dewain Whitmore-DylzGXE_ibU.webm",
"music/normal/Martin Garrix - Animals (Official Video)-gCYcHz2k5x0.webm",
"music/normal/Modjo - Chillin' (Official Video)-hTl0F2cKzLk.webm",
"music/normal/Numb [Official Music Video] - Linkin Park-kXYiU_JCYtU.webm",
"music/normal/Passenger _ Let Her Go (Official Video)-RBumgq5yVrA.webm",
"music/normal/Purple Disco Machine, Sophie And The Giants - Hypnotized (Visualiser)-VbQqV8_Ykow.webm",
"music/normal/Reckless - Olivaw-0SuBLhi236M.webm",
"music/normal/Robin Schulz - Sugar (feat. Francesco Yates) (OFFICIAL MUSIC VIDEO)-bvC_0foemLY.webm",
"music/normal/ROBIN SCHULZ FEAT. ERIKA SIROLA - SPEECHLESS (OFFICIAL VIDEO)-wEzHUFvGO0Q.webm",
"music/normal/SKRILLEX - Bangarang feat. Sirah [Official Music Video]-YJVmu6yttiw.webm",
"music/normal/Skrillex - First Of The Year (Equinox) [Official Music Video]-2cXDgFwE13g.webm",
"music/normal/Smash Mouth - All Star-L_jWHffIx5E.webm",
"music/normal/Sound Of Legend - Tell Me Why (Official Video)-8r39uFM12iU.webm",
"music/normal/Soundtrack Abigail Whistler (Theme Song - Epic Music) - Musique film Abigail Whistler-ZDhLYrlgYxg.webm",
"music/normal/Steve Aoki & Alan Walker - Are You Lonely feat. ISAK (Lyric Video) [Ultra Music]-xdRzsVISVQk.webm",
"music/normal/Swedish House Mafia - Save The World (Official Video)-BXpdmKELE1k.webm",
"music/normal/Taylor Swift - I Knew You Were Trouble-vNoKguSdy4Y.webm",
"music/normal/The Chainsmokers - Don't Let Me Down (Illenium Remix)-s8XIgR5OGJc.webm",
"music/normal/The Immigrant Song- Led Zeppelin 1973-yLarDhciHY0.webm",
"music/normal/Tove Lo - Habits (Stay High) - Hippie Sabotage Remix-SYM-RJwSGQ8.webm",
"music/normal/Tungevaag - Knockout (Official Music Video)-GvK3nq7r69s.webm",
"music/normal/Vengaboys - Boom Boom Boom Boom-llyiQ4I-mcQ.webm",
"music/normal/What I've Done [Official Music Video] - Linkin Park-8sgycukafqQ.webm"
]
];
